<?php

namespace App\Mcp\Tools;

use App\Mcp\Assets\EditorBakes;
use App\Mcp\ToolError;
use App\Models\FoliageAsset;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;

#[Name('bake_foliage_asset')]
#[Description('Live: optimises ("bakes") a foliage asset that is awaiting_bake (imported or generated by Meshy / as a plant card) in the open editor: LODs, impostor and thumbnail, as the studio\'s Foliage page does. Any open map editor works. Waits up to `wait` seconds (default 90); if it is still running afterwards, poll get_asset_status. Foliage types using the asset update live when it is done.')]
class BakeFoliageAsset extends WaterwaysTool
{
    public function schema(JsonSchema $schema): array
    {
        return [
            'asset_id' => $schema->integer()->required(),
            'wait' => $schema->integer()->min(0)->max(240)->description('Seconds to wait for the result (default 90).'),
        ];
    }

    protected function run(Request $request): Response
    {
        $id = (int) $request->get('asset_id');
        $asset = FoliageAsset::query()->find($id) ?? throw new ToolError("No foliage asset {$id}.");
        $result = app(EditorBakes::class)->bake($asset, (int) ($request->get('wait') ?? 90));

        return $this->json([
            'foliage_asset' => GetAssetStatus::foliageSummary($asset->refresh()),
            'editor_map' => $result['editor_map'],
            'next' => match ($asset->status) {
                'ready' => ($asset->meta['warnings'] ?? []) !== []
                    ? 'Ready with warnings (see foliage_asset.bake_warnings): use it with save_foliage_type foliage_asset_id '.$asset->id.', or re-bake / replace the source if a LOD was left out.'
                    : 'Ready: use it with save_foliage_type foliage_asset_id '.$asset->id.'.',
                'failed' => str_contains((string) $asset->status_message, 'background could not be removed')
                    ? 'Optimising failed: the card image\'s background could not be cut out (see foliage_asset.message). Generate it again (asking for a flat magenta background) or upload a PNG with transparency.'
                    : 'Optimising failed; the model may be broken or too heavy. Try another model.',
                default => 'Still optimising: poll get_asset_status in a few seconds.',
            },
        ]);
    }
}
